services:

  # SIS database (PostgreSQL)
  sis-database:
    container_name: sis-database
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5442:5432"
    volumes:
      - ./sis-database/volume:/var/lib/postgresql/data
    networks:
      - sis-net
    restart: unless-stopped

  # SIS REST API (FastAPI)
  sis-api:
    container_name: sis-api
    build:
      context: ./sis-api
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "8000:8000"
    depends_on:
      - sis-database
    networks:
      - sis-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # SIS metadata (pyCSW)
  sis-metadata:
    container_name: sis-metadata
    image: geopython/pycsw:3.0.0-beta1
    environment:
        PYCSW_SERVER_URL: http://localhost:8001
    ports:
      - 8001:8000
    volumes:
      - ./sis-metadata/pycsw.yml:/etc/pycsw/pycsw.yml
      - ./sis-metadata/volume:/records
    networks:
      - sis-net
    depends_on:
      - sis-database
    restart: unless-stopped

  # SIS web services (MapServer)
  sis-web-services:
    container_name: sis-web-services
    image: camptocamp/mapserver:8.4
    ports:
      - "8082:80"
    volumes:
      - ./sis-web-services/volume:/etc/mapserver:ro
    depends_on:
      - sis-database
    networks:
      - sis-net
    restart: unless-stopped

  # SIS web mapping (Openlayers)
  sis-web-mapping:
    container_name: sis-web-mapping
    build: 
      context: ./sis-web-mapping
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - ./sis-web-mapping/public/layer_info.csv:/usr/share/nginx/html/public/layer_info.csv:ro
    environment:
      - NODE_ENV=production
    networks:
      - sis-net
    depends_on:
      - sis-api
      - sis-web-services
      - sis-metadata
    restart: unless-stopped

  # SIS web-server (Nginx reverse proxy)
  sis-nginx:
    image: nginx:alpine
    container_name: sis-nginx
    volumes:
      - ./sis-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./sis-nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      sis-api:
        condition: service_healthy
      sis-database:
        condition: service_started
    networks:
      - sis-net
    restart: unless-stopped

networks:
  sis-net:
    driver: bridge
    name: sis-net
